name: ci-workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'Source/Workflows/**'
      - 'Source/Workflows.Test/**'
      - 'Source/WorkflowImporter/**'
      - 'Source/DeployWorkflowService/**'
  pull_request:
    branches:
      - main
    paths:
      - 'Source/Workflows/**' 
      - 'Source/Workflows.Test/**'
      - 'Source/WorkflowImporter/**'
      - 'Source/DeployWorkflowService/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ./Source/Workflow.sln -s https://api.nuget.org/v3/index.json 
    - name: Build domain
      run: dotnet build ./Source/Workflow.sln --no-restore
    -name: Test
      run: dotnet test ./Source/Workflows.Test/Workflows.Test.csproj --no-build --verbosity normal
